import React,{useState,useEffect} from 'react';
import {SafeAreaView,View,Text,TextInput,Pressable,ScrollView,KeyboardAvoidingView,Platform,StyleSheet,RefreshControl} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {defaultServer,request,roleName,statusName,Role,Session,SavedOrder,User} from './api';
export function Portals({children}:{children:(session:Session,base:string,logout:()=>Promise<void>)=>React.ReactNode}){
 const [base,setBase]=useState(defaultServer);const [session,setSession]=useState<Session|null>(null);const [portal,setPortal]=useState<Role>((process.env.EXPO_PUBLIC_APP_ROLE as Role)||'customer');const [register,setRegister]=useState(false);const [name,setName]=useState('');const [phone,setPhone]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [settings,setSettings]=useState(false);
 const logout=async()=>{if(session)try{await request(base,'/auth/logout',session.token,{});}catch{}setSession(null);setPassword('');setError('');};
 const login=async()=>{if(busy)return;setBusy(true);setError('');try{const result=await request<Session>(base,register?'/auth/register':'/auth/login',undefined,{name,phone,password,role:portal});if(result.user.role!==portal){await request(base,'/auth/logout',result.token,{});throw new Error('Tài khoản này thuộc khu vực '+roleName[result.user.role]+'. Chọn đúng khu vực để đăng nhập.');}setSession(result);setPassword('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 if(session){if(session.user.role==='customer')return <>{children(session,base,logout)}</>;return <Operations session={session} base={base} logout={logout}/>;}
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.mark}><Ionicons name="leaf" size={35} color="white"/></View><Text style={s.brand}>Lâm Thao Ăn Gì?</Text><Text style={s.muted}>Món ngon, mua hộ và giao hàng quanh bạn</Text><View style={s.roles}>{(['customer','driver','admin'] as Role[]).map(r=><Pressable key={r} onPress={()=>{setPortal(r);setRegister(false);setError('');}} style={[s.role,r===portal&&s.selected]}><Ionicons name={r==='customer'?'restaurant-outline':r==='driver'?'bicycle-outline':'shield-checkmark-outline'} size={26} color="#008f46"/><Text style={s.roleText}>{roleName[r]}</Text></Pressable>)}</View><Text style={s.title}>{register?'Tạo tài khoản':'Đăng nhập'} {roleName[portal].toLowerCase()}</Text><Text style={s.muted}>{portal==='driver'?'Đăng ký tài xế cần được admin duyệt trước khi nhận đơn.':portal==='admin'?'Tài khoản quản trị nằm trong thư mục data trên máy tính.':'Đặt món yêu thích và theo dõi đơn của bạn.'}</Text>{register&&<><Text style={s.label}>Họ và tên</Text><TextInput style={s.input} value={name} onChangeText={setName} placeholder="Tên của bạn" maxLength={80} autoComplete="name"/></>}<Text style={s.label}>Số điện thoại</Text><TextInput style={s.input} value={phone} onChangeText={setPhone} placeholder="0912345678" keyboardType="phone-pad" autoComplete="tel"/><Text style={s.label}>Mật khẩu</Text><TextInput style={s.input} value={password} onChangeText={setPassword} placeholder="Ít nhất 8 ký tự" secureTextEntry autoCapitalize="none" autoCorrect={false} maxLength={128} textContentType={register?'newPassword':'password'}/>{error&&<Text accessibilityLiveRegion="polite" style={s.error}>{error}</Text>}<Pressable disabled={busy} style={[s.button,busy&&{opacity:.6}]} onPress={login}><Text style={s.buttonText}>{busy?'Đang xử lý…':register?'Đăng ký':'Đăng nhập'}</Text></Pressable>{portal!=='admin'&&<Pressable style={s.link} onPress={()=>{setRegister(!register);setError('');}}><Text style={s.green}>{register?'Đã có tài khoản? Đăng nhập':'Chưa có tài khoản? Đăng ký'}</Text></Pressable>}<Pressable style={s.link} onPress={()=>setSettings(!settings)}><Text style={s.muted}>Cài đặt kết nối máy tính {settings?'⌃':'⌄'}</Text></Pressable>{settings&&<><Text style={s.label}>Địa chỉ máy chủ</Text><TextInput style={s.input} value={base} onChangeText={setBase} autoCapitalize="none" autoCorrect={false} placeholder="http://192.168.1.10:3001"/><Text style={s.muted}>Tự nhận địa chỉ từ mã QR. Chỉ sửa khi máy tính đổi mạng.</Text></>}<Text style={s.notice}>Bản thử trên Wi-Fi riêng. Chưa có xác thực SMS, thanh toán hoặc phục hồi mật khẩu. Dùng thông tin thử.</Text></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
function Operations({session,base,logout}:{session:Session;base:string;logout:()=>Promise<void>}){
 const [orders,setOrders]=useState<SavedOrder[]>([]);const [users,setUsers]=useState<User[]>([]);const [me,setMe]=useState(session.user);const [tab,setTab]=useState('orders');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [actionBusy,setActionBusy]=useState(false);const admin=me.role==='admin';
 const load=async()=>{setBusy(true);try{const current=await request<{user:User}>(base,'/auth/me',session.token);setMe(current.user);if(admin){const result=await request<{users:User[]}>(base,'/users',session.token);setUsers(result.users);}if(current.user.approved){const result=await request<{orders:SavedOrder[]}>(base,'/orders',session.token);setOrders(result.orders);}setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const action=async(path:string)=>{if(actionBusy)return;setActionBusy(true);try{await request(base,path,session.token,{});await load();}catch(e){setError((e as Error).message);}finally{setActionBusy(false);}};
 const active=orders.filter(o=>o.driver_id===me.id&&!['delivered','cancelled'].includes(o.status));
 const shown=admin?orders:tab==='available'?orders.filter(o=>o.status==='pending'):tab==='history'?orders.filter(o=>o.driver_id===me.id&&['delivered','cancelled'].includes(o.status)):active;
 const actionButton=(title:string,path:string)=><Pressable disabled={actionBusy} style={[s.button,actionBusy&&{opacity:.5}]} onPress={()=>action(path)}><Text style={s.buttonText}>{title}</Text></Pressable>;
 return <SafeAreaView style={s.safe}><View style={s.header}><View><Text style={s.brand}>{admin?'Quản trị':'Tài xế'} Lâm Thao</Text><Text style={s.muted}>Xin chào, {me.name}</Text></View><Pressable onPress={logout} style={s.logout}><Ionicons name="log-out-outline" size={25} color="#008f46"/></Pressable></View><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>}><View style={s.stat}><Text style={s.statNumber}>{admin?orders.length:active.length}</Text><Text style={s.green}>{admin?'Tổng đơn đã tạo':'Đơn đang phụ trách'}</Text><Pressable style={s.link} onPress={load}><Text style={s.green}>↻ Làm mới</Text></Pressable></View><View style={s.tabs}>{(admin?[['orders','Đơn hàng'],['users','Tài khoản']]:[['orders','Đang giao'],['available','Đơn mới'],['history','Lịch sử']]).map(([id,title])=><Pressable key={id} style={[s.tab,tab===id&&s.selected]} onPress={()=>setTab(id)}><Text style={s.green}>{title}</Text></Pressable>)}</View>{error&&<Text style={s.error}>{error}</Text>}{!me.approved?<View style={s.card}><Ionicons name="time-outline" size={38} color="#008f46"/><Text style={s.title}>Đang chờ duyệt</Text><Text style={s.muted}>Admin cần duyệt tài khoản tài xế của bạn. Bấm Làm mới sau khi được duyệt.</Text></View>:admin&&tab==='users'?users.map(u=><View key={u.id} style={s.card}><Text style={s.orderTitle}>{u.name}</Text><Text style={s.muted}>{u.phone} · {roleName[u.role]}</Text><Text style={s.green}>{u.approved?'Đã hoạt động':'Chờ duyệt'}</Text>{u.role==='driver'&&!u.approved&&actionButton('Duyệt tài xế','/users/'+u.id+'/approve')}</View>):<>{shown.length===0&&<Text style={s.muted}>Chưa có đơn ở mục này. Kéo xuống để cập nhật.</Text>}{shown.map(o=><View style={s.card} key={o.id}><View style={s.orderHeading}><Text style={s.orderTitle}>{o.service==='food'?'Đồ ăn':o.service==='shopping'?'Mua hộ':'Giao hàng'}</Text><Text style={s.status}>{statusName[o.status]}</Text></View><Text style={s.muted}>#{o.id.slice(0,8)} · {o.customerName}</Text><Text style={s.summary}>{o.summary}</Text><Text style={s.muted}>Lấy tại: {o.fields.pickup}</Text><Text style={s.muted}>Giao đến: {o.fields.address}</Text>{o.fields.phone&&<Text style={s.muted}>Liên hệ: {o.fields.name} · {o.fields.phone}</Text>}<Text style={s.green}>{o.amount.toLocaleString('vi-VN')} đ{o.service==='shopping'?' · chưa gồm tiền hàng':''}</Text>{o.driverName&&<Text style={s.muted}>Tài xế: {o.driverName}</Text>}{!admin&&o.status==='pending'&&actionButton('Nhận đơn','/orders/'+o.id+'/claim')}{!admin&&o.driver_id===me.id&&['accepted','picked_up'].includes(o.status)&&actionButton(o.status==='accepted'?'Đã lấy hàng':'Đã giao thành công','/orders/'+o.id+'/advance')}{admin&&!['delivered','cancelled'].includes(o.status)&&actionButton('Hủy đơn','/orders/'+o.id+'/cancel')}</View>)}</>}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f7faf8'},content:{padding:24,paddingBottom:40},mark:{width:66,height:66,borderRadius:22,backgroundColor:'#008f46',alignItems:'center',justifyContent:'center',marginTop:20,marginBottom:18},brand:{fontSize:24,fontWeight:'800',color:'#008f46'},muted:{fontSize:12,color:'#6e7f73',lineHeight:20,marginVertical:5},roles:{flexDirection:'row',gap:10,marginVertical:25},role:{flex:1,alignItems:'center',gap:9,paddingVertical:16,borderRadius:14,backgroundColor:'white',borderWidth:1,borderColor:'#e0e9e2'},selected:{backgroundColor:'#ddf5e6',borderColor:'#008f46'},roleText:{fontSize:12,color:'#1e6038',fontWeight:'600'},title:{fontSize:22,fontWeight:'700',color:'#20372a',marginBottom:10},label:{fontSize:12,color:'#476b52',marginTop:16,marginBottom:8},input:{backgroundColor:'white',padding:15,borderRadius:12,borderWidth:1,borderColor:'#dce8df',fontSize:15,color:'#20372a'},button:{backgroundColor:'#008f46',padding:16,borderRadius:12,alignItems:'center',marginTop:20},buttonText:{color:'white',fontSize:15,fontWeight:'700'},link:{minHeight:44,justifyContent:'center',alignItems:'center'},green:{color:'#008f46',fontWeight:'600',fontSize:13},error:{color:'#9a342b',backgroundColor:'#ffebe8',padding:13,borderRadius:10,lineHeight:21,marginTop:12},notice:{fontSize:11,lineHeight:18,color:'#7a897d',marginTop:18},header:{padding:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},logout:{padding:12},stat:{backgroundColor:'#ddf5e6',borderRadius:18,padding:20},statNumber:{fontSize:34,fontWeight:'800',color:'#008f46'},tabs:{flexDirection:'row',gap:8,marginVertical:20},tab:{flex:1,borderRadius:10,paddingVertical:13,alignItems:'center',backgroundColor:'white',borderWidth:1,borderColor:'#e0e9e2'},card:{padding:18,backgroundColor:'white',borderRadius:16,marginBottom:14,borderWidth:1,borderColor:'#e0e9e2'},orderTitle:{fontSize:16,fontWeight:'700',color:'#20372a'},orderHeading:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},status:{fontSize:10,color:'#008f46',backgroundColor:'#e5f7eb',padding:7,borderRadius:7},summary:{fontSize:14,color:'#20372a',lineHeight:22,marginVertical:10}});
